# Generated by Django 5.2.15 on 2026-06-14 01:02

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, verbose_name='email secundario')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nombre')),
                ('display_alias', models.CharField(blank=True, max_length=150, verbose_name='alias visible')),
                ('preferred_locale', models.CharField(choices=[('es-mx', 'Español de México'), ('en-us', 'English United States')], default='es-mx', max_length=5, verbose_name='idioma preferido')),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=64, verbose_name='zona horaria')),
                ('user_type', models.CharField(choices=[('FREE', 'Gratuito'), ('PREMIUM', 'Premium'), ('BUSINESS_ADMIN', 'Admin negocio'), ('TECH_ADMIN', 'Admin técnico')], default='FREE', max_length=20, verbose_name='tipo de usuario')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FROZEN', 'Congelado'), ('PENDING_DELETION', 'Pendiente de borrado'), ('DELETED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='estado')),
                ('is_staff', models.BooleanField(default=False, help_text='Permite acceder al administrador de Django.', verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, help_text='Desactiva el inicio de sesión sin borrar el usuario.', verbose_name='activo para autenticación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
