# Generated by Django 5.2.15 on 2026-06-15 23:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_system', models.BooleanField(default=False, verbose_name='es del sistema')),
                ('font_category', models.CharField(choices=[('SERIF', 'Serif'), ('SANS_SERIF', 'Sans serif')], default='SERIF', max_length=20, verbose_name='categoría tipográfica')),
                ('font_heading', models.CharField(default='Libre Baskerville', max_length=120, verbose_name='fuente de títulos')),
                ('font_body', models.CharField(default='Merriweather', max_length=120, verbose_name='fuente de cuerpo')),
                ('heading_size', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='tamaño de títulos')),
                ('body_size', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5, verbose_name='tamaño de cuerpo')),
                ('line_spacing', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4, verbose_name='interlineado')),
                ('paragraph_spacing', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='espaciado entre párrafos')),
                ('margin_top', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='margen superior')),
                ('margin_bottom', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='margen inferior')),
                ('margin_left', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='margen izquierdo')),
                ('margin_right', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='margen derecho')),
                ('text_alignment', models.CharField(choices=[('LEFT', 'Izquierda'), ('JUSTIFY', 'Justificado'), ('CENTER', 'Centrado'), ('RIGHT', 'Derecha')], default='JUSTIFY', max_length=10, verbose_name='alineación de texto')),
                ('first_line_indent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='sangría de primera línea')),
                ('scene_separator', models.CharField(blank=True, default='***', max_length=80, verbose_name='separador de escena')),
                ('include_page_numbers', models.BooleanField(default=True, verbose_name='incluir números de página')),
                ('include_table_of_contents', models.BooleanField(default=False, verbose_name='incluir tabla de contenidos')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='configuración JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_templates', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'plantilla de estilo',
                'verbose_name_plural': 'plantillas de estilo',
                'ordering': ['-is_system', 'name'],
                'indexes': [models.Index(fields=['is_system', 'name'], name='styles_styl_is_syst_885c7b_idx'), models.Index(fields=['user', 'name'], name='styles_styl_user_id_83d910_idx'), models.Index(fields=['font_category'], name='styles_styl_font_ca_e63150_idx')],
            },
        ),
    ]
