# Generated by Django 5.2.15 on 2026-06-15 22:50

import apps.characters.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('alias', models.CharField(blank=True, max_length=180, verbose_name='alias')),
                ('image', models.FileField(blank=True, upload_to=apps.characters.models.character_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'], message='Sube una imagen JPG, JPEG, PNG, GIF o WEBP.')], verbose_name='imagen')),
                ('importance', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIA', 'Secundaria'), ('FIGURANTE', 'Figurante')], default='SECUNDARIA', max_length=20, verbose_name='importancia')),
                ('narrative_role', models.CharField(choices=[('PROTAGONISTA', 'Protagonista'), ('DEUTERAGONISTA', 'Deuteragonista'), ('TRITAGONISTA', 'Tritagonista'), ('ANTAGONISTA', 'Antagonista'), ('PERSONAJE_IMPORTANTE', 'Personaje importante'), ('SECUNDARIO', 'Secundario'), ('INCIDENTAL', 'Incidental'), ('OTRO', 'Otro')], default='SECUNDARIO', max_length=30, verbose_name='rol narrativo')),
                ('custom_narrative_role', models.CharField(blank=True, max_length=180, verbose_name='rol narrativo personalizado')),
                ('physical_description', models.TextField(blank=True, verbose_name='descripción física')),
                ('psychological_description', models.TextField(blank=True, verbose_name='descripción psicológica')),
                ('biography', models.TextField(blank=True, verbose_name='biografía')),
                ('motivations', models.TextField(blank=True, verbose_name='motivaciones')),
                ('goals', models.TextField(blank=True, verbose_name='objetivos')),
                ('fears', models.TextField(blank=True, verbose_name='miedos')),
                ('virtues', models.TextField(blank=True, verbose_name='virtudes')),
                ('flaws', models.TextField(blank=True, verbose_name='defectos')),
                ('character_arc', models.TextField(blank=True, verbose_name='arco del personaje')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('completion_status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PARTIAL', 'Parcial'), ('COMPLETE', 'Completo')], default='DRAFT', max_length=20, verbose_name='estado de construcción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'personaje',
                'verbose_name_plural': 'personajes',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterDramaticRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HEROE', 'Héroe'), ('HEROINA', 'Heroína'), ('VILLANO', 'Villano'), ('INTERES_ROMANTICO', 'Interés romántico'), ('MENTOR', 'Mentor'), ('ALIADO', 'Aliado'), ('RIVAL', 'Rival'), ('TRAIDOR', 'Traidor'), ('PROTEGIDO', 'Protegido'), ('CATALIZADOR', 'Catalizador'), ('NARRADOR', 'Narrador'), ('ALIVIO_COMICO', 'Alivio cómico'), ('OTRO', 'Otro')], max_length=30, verbose_name='papel dramático')),
                ('custom_role', models.CharField(blank=True, max_length=180, verbose_name='papel personalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dramatic_roles', to='characters.character', verbose_name='personaje')),
            ],
            options={
                'verbose_name': 'papel dramático',
                'verbose_name_plural': 'papeles dramáticos',
                'ordering': ['character', 'role'],
            },
        ),
        migrations.CreateModel(
            name='CharacterMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.CharField(choices=[('APPEARS', 'Aparece'), ('MENTIONED', 'Mencionado'), ('POV', 'Punto de vista'), ('NARRATOR', 'Narrador'), ('IMPORTANT_FOR_SCENE', 'Importante para la escena')], max_length=30, verbose_name='tipo de mención')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='characters.character', verbose_name='personaje')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_mentions', to='manuscripts.manuscriptnode', verbose_name='nodo de manuscrito')),
            ],
            options={
                'verbose_name': 'mención de personaje',
                'verbose_name_plural': 'menciones de personajes',
                'ordering': ['character', 'node', 'mention_type'],
            },
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['project', 'name'], name='characters__project_6136c7_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['project', 'importance'], name='characters__project_72573f_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['project', 'narrative_role'], name='characters__project_aac142_idx'),
        ),
    ]
