# Generated by Django 5.2.15 on 2026-06-16 00:44

import apps.exports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0001_initial'),
        ('projects', '0001_initial'),
        ('styles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('HTML', 'HTML'), ('DOCX', 'DOCX'), ('PDF', 'PDF'), ('EPUB', 'EPUB')], default='HTML', max_length=10, verbose_name='formato')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('DONE', 'Terminada'), ('FAILED', 'Fallida')], default='PENDING', max_length=20, verbose_name='estado')),
                ('file', models.FileField(blank=True, upload_to=apps.exports.models.export_upload_path, verbose_name='archivo')),
                ('error_message', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='iniciado')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='projects.project', verbose_name='proyecto')),
                ('root_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='manuscripts.manuscriptnode', verbose_name='nodo raíz')),
                ('style_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='styles.styletemplate', verbose_name='plantilla de estilo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'trabajo de exportación',
                'verbose_name_plural': 'trabajos de exportación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'project', '-created_at'], name='exports_exp_user_id_253e53_idx'), models.Index(fields=['status', 'format'], name='exports_exp_status_adfae1_idx'), models.Index(fields=['created_at'], name='exports_exp_created_172976_idx')],
            },
        ),
    ]
