# Generated by Django 5.2.15 on 2026-06-14 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=2, verbose_name='idioma')),
                ('locale', models.CharField(choices=[('es-mx', 'Español de México'), ('en-us', 'English United States')], default='es-mx', max_length=5, verbose_name='locale')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FROZEN', 'Congelado'), ('PENDING_DELETION', 'Pendiente de borrado'), ('DELETED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='congelado')),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='borrado solicitado')),
                ('scheduled_deletion_at', models.DateTimeField(blank=True, null=True, verbose_name='borrado programado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['user', 'status'], name='projects_pr_user_id_40c3f7_idx'), models.Index(fields=['user', '-created_at'], name='projects_pr_user_id_3cbd31_idx')],
            },
        ),
    ]
