# Generated by Django 5.2.15 on 2026-06-15 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('manuscripts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('NOTE', 'Nota'), ('IDEA', 'Idea'), ('TASK', 'Pendiente')], default='NOTE', max_length=10, verbose_name='tipo')),
                ('title', models.CharField(max_length=220, verbose_name='título')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Terminada'), ('DISCARDED', 'Descartada')], default='OPEN', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10, verbose_name='prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminada')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_notes', to='characters.character', verbose_name='personaje')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='manuscripts.manuscriptnode', verbose_name='nodo de manuscrito')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['project', '-updated_at', 'title'],
                'indexes': [models.Index(fields=['project', 'note_type'], name='notes_note_project_3e1dd8_idx'), models.Index(fields=['project', 'status'], name='notes_note_project_8c885a_idx'), models.Index(fields=['project', 'priority'], name='notes_note_project_fc78ed_idx'), models.Index(fields=['project', '-updated_at'], name='notes_note_project_c7eb0b_idx')],
            },
        ),
    ]
