# Generated by Django 5.2.15 on 2026-06-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('BOOK', 'Libro'), ('PART', 'Parte'), ('CHAPTER', 'Capítulo'), ('SCENE', 'Escena'), ('FRAGMENT', 'Fragmento')], default='BOOK', max_length=20, verbose_name='tipo de nodo')),
                ('title', models.CharField(max_length=220, verbose_name='título')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('DRAFT', 'Borrador'), ('REVIEW', 'Revisión'), ('FINISHED', 'Terminado'), ('PUBLISHABLE', 'Publicable'), ('PUBLISHED', 'Publicado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='posición')),
                ('is_publishable', models.BooleanField(default=False, verbose_name='es publicable')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='conteo de palabras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='manuscripts.manuscriptnode', verbose_name='padre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_nodes', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'nodo de manuscrito',
                'verbose_name_plural': 'nodos de manuscrito',
                'ordering': ['project', 'parent_id', 'position', 'created_at'],
                'indexes': [models.Index(fields=['project', 'parent', 'position'], name='manuscripts_project_777ec5_idx'), models.Index(fields=['project', 'node_type'], name='manuscripts_project_ab68ab_idx'), models.Index(fields=['project', 'status'], name='manuscripts_project_a43aa7_idx')],
            },
        ),
    ]
